# Generated by Django 3.2.5 on 2022-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('job', models.CharField(max_length=32, verbose_name='工作类型')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('state', models.SmallIntegerField(choices=[(0, '空闲'), (1, '忙碌')], default=0, verbose_name='状态')),
            ],
        ),
    ]
