# Generated by Django 3.2.5 on 2022-04-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=32, verbose_name='项目名')),
                ('state', models.SmallIntegerField(choices=[(0, '闲置'), (1, '进行中')], default=0, verbose_name='状态')),
                ('responser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wangapp.freeemployee', verbose_name='负责人')),
            ],
        ),
    ]
