# Generated by Django 3.2.5 on 2022-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0003_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='projecttype',
            field=models.CharField(default=None, max_length=32, verbose_name='项目类型'),
            preserve_default=False,
        ),
    ]
