# Generated by Django 3.2.5 on 2022-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0006_contrast_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrast',
            name='name',
            field=models.CharField(default=None, max_length=32, verbose_name='合同名'),
        ),
    ]
