# Generated by Django 3.2.5 on 2022-04-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0007_contrast_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrast',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '未到期'), (1, '进行中'), (2, '已到期')], default=0, verbose_name='状态'),
        ),
    ]
