# Generated by Django 3.2.5 on 2022-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0008_alter_contrast_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(default=None, max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='freeemployee',
            name='password',
            field=models.CharField(default=None, max_length=32, verbose_name='密码'),
        ),
    ]
