# Generated by Django 3.2.5 on 2022-04-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0009_auto_20220405_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeemployee',
            name='state',
        ),
    ]
